export const CARS = [
  'lada granta 2190', 'lada vesta 2180', 'kia rio 4 (fb)', 'lada niva travel (21214)',
  'chery tiggo 7 pro (t21)', 'hyundai solaris ii (hc)', 'hyundai creta (su2)', 'haval jolion (a23)',
  'lada niva legend (2121)', 'renault duster i (hsa)', 'geely coolray (jx11)', 'lada largus (2191)',
  'volkswagen polo v (6r)', 'renault logan ii (l90)', 'toyota rav4 iv (ca40)', 'skoda rapid (nh)',
  'kia seltos (sp2)', 'chery tiggo 4 (t12)', 'toyota camry xv70', 'mazda cx-5 ii (kf)',
  'hyundai tucson iii (tl)', 'ford focus iii (bm)', 'ford fiesta vii (jaa)', 'nissan qashqai ii (j11)',
  'volkswagen golf vii (5g)', 'audi a4 b9', 'bmw 3 series g20', 'mercedes c-class w205',
  'volvo s60 ii (p2)', 'peugeot 508 i (r82)', 'toyota corolla e210', 'honda civic x',
  'honda cr-v v (rw)', 'ford mustang vi (s550)', 'chevrolet corvette c7', 'subaru outback v (bs)',
  'jeep wrangler jl', 'toyota highlander (xu70)', 'ford explorer vi', 'nissan x-trail t32',
  'skoda superb iii', 'volvo xc60 i (ad)', 'vw tiguan ii (ad)', 'honda accord ix',
  'hyundai sonata lf', 'kia sportage ql', 'mazda 6 g2 (gh)', 'acura rdx tb5', 'bmw x5 g05',
  'audi q5 80a', 'mercedes glc x253', 'volkswagen passat b8', 'hyundai elantra md',
  'skoda octavia a7', 'renault sandero ii', 'ford mondeo mk5', 'peugeot 3008 i (p84)',
  'citroen c4 picasso ii', 'nissan tiida c13', 'mitsubishi outlander iii', 'toyota camry xv70',
  'subaru forester v (sf)', 'mitsubishi pajero sport (kh)', 'kia ceed jd', 'seat leon 5f',
  'renault logan 1 (l90)', 'skoda fabia mk2', 'fiat doblo (263)', 'ford transit custom',
  'peugeot partner tepee', 'renault kangoo (x61)', 'mercedes vito w447', 'vw transporter t6',
  'toyota avensis t27', 'mazda cx-9 tc', 'nissan murano z52', 'audi a6 c7', 'bmw 5 series g30',
  'mercedes e-class w213', 'volvo xc90 i (first gen)', 'jeep grand cherokee wk2', 'kia carnival yp',
  'hyundai staria', 'kia carnival ka4', 'honda odyssey rb3', 'chevrolet tahoe (gmt900)',
  'nissan patrol y62', 'toyota land cruiser prado (j150)', 'land rover discovery 5 (l462)',
  'audi q7 4m', 'bmw x3 g01', 'mercedes gle w167', 'volkswagen touareg 7p', 'volvo xc40',
  'mini countryman f60', 'smart fortwo c453', 'toyota yaris (xp13)', 'hyundai i30 (pd)',
  'kia rio 5 (yb)', 'mitsubishi lancer x (cx)', 'subaru impreza v (gt)', 'skoda kodiaq (ns)',
  'renault kaptur 1 (hsa2)', 'nissan almera g15', 'chevrolet spark m300', 'fiat 500x',
  'citroen c3 aircross', 'peugeot 2008 i (pj)', 'vw polo sedan (capa)'
];
